#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP
domain=$1
sub=$2

records () {
	if [ "$2" ]
	then
		var=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:')
		record="$(awk '{print $4}' <<<"$var")"
		ipa="$(awk '{print $5}' <<<"$var")"
		printf "The subdomain %s is a %s record and points to %s\n" $sub $record $ipa
	else
		for s in 'www' 'lb-01' 'web-01' 'web-02'
		do
			var=$(dig "$s.$domain" | grep -A1 'ANSWER SECTION:')
                	record="$(awk '{print $4}' <<<"$var")"

                	ipa="$(awk '{print $5}' <<<"$var")"
			printf "The subdomain %s is a %s record and points to %s\n" $s $record $ipa
		done
	fi
}

records "$1" "$2"
