#!/usr/bin/env bash
# configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" >> /var/www/html/index.html
sudo systemctl restart nginx
