#!/usr/bin/env bash
# configures a new Ubuntu machine
rewrite="server_name.*/a rewrite ^/redirect_me"
new_string="https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "s/$rewrite/$new_string/" $file
sudo service nginx restart
