#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get install haproxy=1.8.\*

host1=$(curl -sI 35.190.170.193 | grep X-Served-By | awk '{ print $2 }' | rev | cut -c 2- | rev)
host2=$(curl -sI 3.80.222.135 | grep X-Served-By | awk '{ print $2 }' | rev | cut -c 2- | rev)

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend http-in
	mode http
	bind *:80
	default_backend webservers

backend webservers
	balance roundrobin
	server ${host1} 35.190.170.193:check
	server ${host2} 3.80.222.135:check

EOF

echo -e '\n#Enable HAProxy to be started by the init script\nENABLED=1' >> /etc/default/haproxy
service haproxy restart
