#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get install haproxy=1.8.\*
service nginx restart
