#!/usr/bin/env bash
# Loops from 1 to 10 and display below
str="Holberton School"
bl="bad luck"
gl="good luck"
counter=1
while [ "$counter" -le 10 ]
  do
    if [ "$counter" -eq 4 ]
    then
       echo "$bl"
    elif [ "$counter" -eq 8 ]
    then
       echo "$gl"
    else
       echo "$str"
    fi
    ((counter++))
  done
