#!/usr/bin/env bash
# Displays numbers from 1 to 20, with conditions
china="bad luck from China"
japan="bad luck from Japan"
italy="bad luck from Italy"
counter=1
while [ "$counter" -le 20 ]
  do
    echo $counter
    case $counter in

      4)
        echo "$china"
        ;;

      9)
        echo "$japan"
        ;;

      17)
        echo "$italy"
        ;;
    esac

    ((counter++))
   done
