#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
hour=0
minute=0
while [ $hour -lt 24 ]
  do
    echo "Hour: $hour"
    minute=1
    while [ $minute -lt 60 ]
      do
        echo $minute
        ((minute++))
      done
    ((hour++))
  done
