#!/usr/bin/env bash
# Gives information about holbertonschool file
my_file="./holbertonschool"
if [ -e "$my_file" ]
  then
    echo "holbertonschool file exists"
else
  echo "holbertonschool file does not exist"
fi

if [ -s "$my_file" ]
  then
    echo "holbertonschool file is not empty"
else
  echo "holbertonschool file is empty"
fi

if [ -f "$my_file" ]
  then
    echo "holbertonschool is a regular file"
fi
