#!/usr/bin/env bash
# Task 0
sudo apt-get update
sudo apt-get -y install apache2
echo "ServerName localhost" >> sudo tee -a /etc/apache2/apache2.conf
sudo echo "Hello Holberton"
sudo service apache2 start
