#!/usr/bin/env bash
# 7 lines or less
sudo chown -R nginx:nginx /etc/nginx/
sudo sed -i '4a user nginx;' /etc/nginx/nginx.conf
sudo -u nginx sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
